### ISSUE TITLE
Modelica.Electrical.PowerConverters.ACDC.Filter uses undeclared useFilter parameter

### ISSUE THREAD

**Issue by JoeRiel** [modelica/Modelica#2150] opened 2017-01-27 21:23 UTC
The Filter model uses useFilter in the annotation of yStart. However useFilter is not a parameter of Filter. This prevents the yStart parameter from being displayed:
  `parameter Real yStart=0 "Start value of output"
          annotation (Dialog(enable=useFilter));`

**Comment by beutlich** [comment] 2017-01-27 22:25
Probably a duplicate of #2003?

**Comment by beutlich** [comment] 2017-01-31 09:32
@christiankral  I fixed it in branches master and maint/3.2.2.

**Closed by beutlich** 2017-01-31 09:32 UTC
Labels: L: Electrical.PowerConverters
