### ISSUE TITLE
Reading data fails in ComiTimeTable after 1e+07 seconds

### ISSUE THREAD

**Issue by annvdm** [modelica/Modelica#2283] opened 2017-07-20 11:55 UTC
When A `CombiTimeTable` is used to read a txt-file that contains data for a whole year, the sampling of the data changes once the time becomes larger than 1e+07. 
See screenshot below, where sampling of the data clearly changes at this time, even though the source data (i.e. the txt-file) does not show this change.

![image](https://user-images.githubusercontent.com/23457819/28416001-78be931e-6d52-11e7-8d31-fcf4dde38b97.png)

I used:
`Modelica.Blocks.Sources.CombiTimeTable tab(
tableOnFile=true, 
tableName="data",
fileName="test.txt",
columns=2:2);`

Data file:
https://www.dropbox.com/s/cpsh1t4uvyzx4nc/test.txt?dl=0

**Comment by tbeu** [comment] 2017-07-24 21:30
Duplicate of #2282?

**Comment by Mathadon** [comment] 2017-07-25 06:39
It possibly has the same cause, but the 'symptom' is different: the resolution seems wrong, not the interpolation type?

**Comment by tbeu** [comment] 2017-08-03 19:16
The data in test.txt is stored with only three significant digits. The problem gets apparent first on lines 171 and 172, which read
```
1.01E+05 ...
1.01E+05 ...
```
but rather should be of higher precision
```
1.006E+05 ...
1.012E+05 ...
```
.

**Closed by tbeu** 2017-08-03 19:16 UTC
Labels: L: C-Sources
